### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by gongbangrui** [mx-space/docs-legacy#13]
ubuntu 18.04
快速部署时到外网访问这步
http://localhost:2333/#/qaqdmin/setup
显示{"ok":0,"message":"Cannot GET /"}

**Comment by gongbangrui** [comment]
无法访问后台面板

**Comment by ttimochan** [comment]
访问http://localhost:2333/qaqdmin  若没有注册会跳转到注册页面，如果注册了，则跳转到登陆页面
